easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Action
        - App\Entity\Asset
        - App\Entity\Branch
        - App\Entity\Detection
        - App\Entity\Family
        - App\Entity\Office
        - App\Entity\Person
        - App\Entity\Product
        - App\Entity\RemediationAction
        - App\Entity\Status
        - App\Entity\Tag
        - App\Entity\Type
        - App\Entity\Vendor
        - App\Entity\Vlan
        - App\Entity\Vulnerability
        - App\Entity\VulnerabilityDetected
